name: task_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter


  flutter_svg:
  get_it:
  auto_route: ^6.0.5
  cupertino_icons: ^1.0.2
  freezed:
  freezed_annotation:
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^6.0.3
  build_runner:
  flutter_gen_runner:
  flutter_lints:
  json_serializable:

flutter_gen:
  output: lib/gen/=
  line_length: 120

  # Optional
  integrations:
    flutter_svg: true


flutter:
  uses-material-design: true

  assets:
    # Icons
    - assets/icons/
